config/routes.rb
Rails.application.routes.draw do
  get "", to: redirect('/comics/index')
  get 'comics/index'
  post "add_vote", to: 'upvotes#add_vote'
  delete "remove_vote", to: 'upvotes#remove_vote'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  require 'digest/md5'
  require 'rest-client'

  BASE_URL = "https://gateway.marvel.com:443/v1/public/"

  def self.get_comics offset
    parsed_data = JSON.parse(call_api_fetch_comics(offset))
    parsed_data['data']['results'].map { |results| {"id" => results["id"], "title" => results["title"], "image" => image(results)} }
  end
  
  def self.get_comics_by_character(name, offset)
    character = JSON.parse(call_api_fetch_character(name))
    return {} if character['data']['count'] <= 0
    character_id = character['data']['results'][0]['id']
    parsed_data = JSON.parse(call_api_fetch_comics_by_character(offset, character_id))
    parsed_data['data']['results'].map { |results| {"id" => results["id"], "title" => results["title"], "image" => image(results)} }
  end

  private

  def self.call_api_fetch_comics offset
    RestClient.get("#{BASE_URL}comics?apikey=#{Rails.application.credentials[:MARVEL_API][:PUBLIC_KEY]}&hash=#{Digest::MD5.hexdigest(Rails.application.credentials[:MARVEL_API][:HASH])}&ts=1234&orderBy=-onsaleDate&offset=#{offset}")
  end

  def self.call_api_fetch_character name
    RestClient.get("#{BASE_URL}characters?apikey=#{Rails.application.credentials[:MARVEL_API][:PUBLIC_KEY]}&hash=#{Digest::MD5.hexdigest(Rails.application.credentials[:MARVEL_API][:HASH])}&ts=1234&name=#{name}")
  end

  def self.call_api_fetch_comics_by_character(offset, id_character)
    RestClient.get("#{BASE_URL}comics?apikey=#{Rails.application.credentials[:MARVEL_API][:PUBLIC_KEY]}&hash=#{Digest::MD5.hexdigest(Rails.application.credentials[:MARVEL_API][:HASH])}&ts=1234&orderBy=-onsaleDate&offset=#{offset}&characters=#{id_character}")
  end


  def self.image results
    "#{results["thumbnail"]["path"]}/portrait_uncanny.#{results["thumbnail"]["extension"]}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @offset = params.fetch(:offset, 0).to_i
    @offset = 0 if @offset <= 0
    if params.has_key?(:search) && params.fetch(:search).present?
      @comics = Comic.get_comics_by_character(params.fetch(:search), @offset)
    else
      @comics = Comic.get_comics(@offset)
    end
    @comics
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

    def add_vote
        session[:comics_upvoted] = [] if session[:comics_upvoted].nil?
        session[:comics_upvoted] << params[:id]
        return redirect_to '/comics/index?search=' + params[:search_term] if params[:search_term].present?
        redirect_to '/comics/index'
    end

    def remove_vote
        session[:comics_upvoted].delete(params[:id])
        return redirect_to '/comics/index?search=' + params[:search_term] if params[:search_term].present?
        redirect_to '/comics/index'

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comics/index.html.erb
<nav class="navbar sticky-top">
    <div class="row mx-auto">
        <div class="col-9 ">
            <div class="marvel-logo">
                <%= image_tag "marvel_logo.png", class: "image" %>
            </div>
            <%= form_tag comics_index_path, local: true, method: :get  do %>
                <div class="form-control input-group-btn search-button">
                    <%= text_field_tag :search, params[:search], placeholder: "ex: Wolverine" %>
                </div>
            <% end %>
        </div>
    </div>
</nav>
<div class="container">	
	<% @comics.each do |comic| %>
        <div class="comic-card">
            <div class="comic-header">
                <%= image_tag comic["image"], :class => "img_preview" %>
                <div class="heart_effect">
                 <%= %>
                    <% if comic["id"].to_s.in?(session[:comics_upvoted])  %>
                        <%= button_to remove_vote_path(:id => comic["id"], :search_term => params[:search] ), method: "delete", class: "button_heart" do %>
                            <%= image_tag 'heart_on.png' %>
                        <% end %>
                    <% else %>
                        <%= button_to add_vote_path(:id => comic["id"], :search_term => params[:search]), class: "button_heart" do %>
                            <%= image_tag 'heart_off.png' %>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="comic-content">
                <div class="comic-content-header">
                    <h4 class="comic-title"> 
                        <%= comic["title"] %> 
                    </h4>
                </div>
            </div>
        </div>
    <% end %>
	<div class="btn footer">
        <%= link_to "PREVIOUS PAGE", comics_index_path(offset: @offset - 20), :class => "btn btn-left" %>
	    <%= link_to "NEXT PAGE", comics_index_path(offset: @offset + 20), :class => "btn btn-right" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarvelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>